import type {
  AppNotification,
  Category,
  Conversation,
  Order,
  Post,
  StoryItem,
} from "@/types";

export const currentUser = {
  id: "me",
  name: "Abdulhamid Ore",
  handle: "abdulhamid",
  title: "Student & Innovator",
  verified: true,
  tier: "nin" as const,
  walletBalance: 120500,
  trustScore: "Verified · Level 3",
};

export const stories: StoryItem[] = [
  { id: "create", label: "Create Post", isCreate: true },
  { id: "for-you", label: "For You" },
  { id: "following", label: "Following" },
  { id: "universities", label: "Universities" },
  { id: "vendors", label: "Vendors" },
  { id: "artists", label: "Artists" },
];

export const categories: Category[] = [
  { id: "phones", label: "Phones", icon: "smartphone" },
  { id: "fashion", label: "Fashion", icon: "shirt" },
  { id: "electronics", label: "Electronics", icon: "headphones" },
  { id: "books", label: "Books", icon: "book-open" },
  { id: "food", label: "Food", icon: "utensils" },
  { id: "more", label: "More", icon: "grid-2x2" },
];

export const posts: Post[] = [
  {
    id: "p1",
    author: {
      id: "tobi-lux",
      name: "Tobi Lux",
      handle: "tobilux.ng",
      verified: true,
      tier: "nin",
    },
    timeAgo: "2h",
    title: "iPhone 13 Pro Max (256GB)",
    description: "Clean, like new. Face ID perfect.",
    location: "Unilag, Lagos",
    price: 680000,
    productImageLabel: "iPhone 13 Pro Max",
    categoryId: "phones",
    comments: 24,
    reposts: 17,
    likes: 105,
    nearby: true,
    specs: ["256GB storage", "Face ID working perfectly", "Battery health 91%"],
  },
  {
    id: "p2",
    author: {
      id: "zainab",
      name: "Zainab",
      handle: "zai_creates",
      verified: true,
      tier: "business",
    },
    timeAgo: "3h",
    title: "Handmade Beaded Ring",
    description: "Custom sizes. Beautifully made",
    location: "OAU, Ile-Ife",
    price: 2500,
    productImageLabel: "Beaded Ring",
    categoryId: "fashion",
    comments: 12,
    reposts: 8,
    likes: 46,
    specs: ["Made to order", "Adjustable sizing", "Ships within 2 days"],
  },
  {
    id: "p3",
    author: {
      id: "techie-hub",
      name: "Techie Hub",
      handle: "techiehub",
      verified: true,
      tier: "business",
    },
    timeAgo: "4h",
    title: "Dell XPS 15 (16GB RAM, 512GB SSD)",
    description: "Fast, neat and super smooth.",
    location: "Funso, Akoka",
    price: 550000,
    productImageLabel: "Dell XPS 15",
    categoryId: "electronics",
    comments: 19,
    reposts: 13,
    likes: 70,
    nearby: true,
    specs: ["16GB RAM", "512GB SSD", "Intel Core i7, 11th Gen"],
  },
  {
    id: "p4",
    author: {
      id: "campus-threads",
      name: "Campus Threads",
      handle: "campusthreads",
      verified: true,
      tier: "business",
    },
    timeAgo: "5h",
    title: "Ankara Print Jacket (Unisex)",
    description: "Handmade, breathable fabric, fits true to size.",
    location: "Yaba, Lagos",
    price: 18500,
    productImageLabel: "Ankara Jacket",
    categoryId: "fashion",
    comments: 9,
    reposts: 4,
    likes: 61,
    sponsored: true,
    specs: ["100% cotton Ankara", "Sizes S-XXL", "Machine washable"],
  },
  {
    id: "p5",
    author: {
      id: "mama-ngozi",
      name: "Mama Ngozi Kitchen",
      handle: "mamangozi",
      verified: true,
      tier: "nin",
    },
    timeAgo: "6h",
    title: "Jollof Rice Combo Pack (Serves 4)",
    description: "Freshly made, delivered hot. Pre-order for weekends.",
    location: "Akoka, Lagos",
    price: 8000,
    productImageLabel: "Jollof Combo",
    categoryId: "food",
    comments: 31,
    reposts: 6,
    likes: 142,
    nearby: true,
    specs: ["Serves 4 people", "Includes chicken & plantain", "Same-day delivery"],
  },
  {
    id: "p6",
    author: {
      id: "booknest",
      name: "BookNest NG",
      handle: "booknest",
      verified: true,
      tier: "business",
    },
    timeAgo: "8h",
    title: "Atomic Habits + Study Guide Bundle",
    description: "Almost new, no highlights. Great for freshers.",
    location: "OAU, Ile-Ife",
    price: 6500,
    productImageLabel: "Book Bundle",
    categoryId: "books",
    comments: 5,
    reposts: 2,
    likes: 28,
    specs: ["Paperback", "Includes free study planner", "Ships nationwide"],
  },
  {
    id: "p7",
    author: {
      id: "gadget-plug",
      name: "Gadget Plug",
      handle: "gadgetplug",
      verified: true,
      tier: "premium",
    },
    timeAgo: "10h",
    title: "Sony WH-1000XM4 Headphones",
    description: "Noise cancelling, barely used, comes with case.",
    location: "Ikeja, Lagos",
    price: 195000,
    productImageLabel: "Sony Headphones",
    categoryId: "electronics",
    comments: 22,
    reposts: 11,
    likes: 89,
    sponsored: true,
    specs: ["Active noise cancellation", "30hr battery life", "Original case included"],
  },
  {
    id: "p8",
    author: {
      id: "sneakerlab",
      name: "SneakerLab",
      handle: "sneakerlab.ng",
      verified: false,
      tier: "unverified",
    },
    timeAgo: "12h",
    title: "Nike Air Force 1 (Size 42)",
    description: "Fairly used, no box. Clean sole.",
    location: "Unilag, Lagos",
    price: 32000,
    productImageLabel: "Air Force 1",
    categoryId: "fashion",
    comments: 14,
    reposts: 3,
    likes: 54,
    nearby: true,
    specs: ["Size 42 (EU)", "No original box", "Minor wear on toe"],
  },
];

export const productDetail = {
  ...posts[0],
  seller: {
    id: "tobi-lux",
    name: "Tobi Lux Store",
    handle: "tobilux.ng",
    verified: true,
    tier: "nin" as const,
    rating: 4.9,
    ratingCount: 2314,
    successRate: 98,
    responseTime: "8 mins",
  },
};

export const orders: Order[] = [
  {
    id: "EUP87659",
    itemLabel: "iPhone 13 Pro Max",
    status: "waiting",
    statusLabel: "Waiting for Seller",
    amount: 320000,
    meta: "May 20, 2026",
  },
  {
    id: "EUP87658",
    itemLabel: "Dell XPS 15",
    status: "in_transit",
    statusLabel: "In Transit",
    amount: 450000,
    meta: "Estimated delivery: May 23",
    progress: 60,
  },
  {
    id: "EUP87657",
    itemLabel: "Studio Headphones",
    status: "awaiting_confirmation",
    statusLabel: "Awaiting Confirmation",
    amount: 280000,
    meta: "Confirm receipt to release payment · 2d : 14h : 32m left",
  },
  {
    id: "EUP87656",
    itemLabel: "HP Pavilion 15",
    status: "completed",
    statusLabel: "Completed",
    amount: 200000,
    meta: "Payment released · May 18, 2026",
  },
];

export const conversations: Conversation[] = [
  {
    id: "c1",
    author: {
      id: "techsavvy",
      name: "TechSavvy Store",
      handle: "techsavvy",
      verified: true,
      tier: "business",
    },
    lastMessage: "Yes, it's still available.",
    timeAgo: "2m",
    unread: 1,
    category: "seller",
    messages: [
      { id: "m1", fromMe: true, text: "Hi, is the MacBook still available?", timeAgo: "10:02 AM" },
      { id: "m2", fromMe: false, text: "Yes, it's still available.", timeAgo: "10:04 AM" },
      { id: "m3", fromMe: false, text: "Would you like to arrange a meetup or delivery?", timeAgo: "10:04 AM" },
    ],
  },
  {
    id: "c2",
    author: {
      id: "chidi",
      name: "Chidi Okonkwo",
      handle: "chidi.o",
      verified: false,
      tier: "unverified",
    },
    lastMessage: "Can we meet on campus?",
    timeAgo: "15m",
    unread: 2,
    category: "buyer",
    messages: [
      { id: "m1", fromMe: false, text: "Hey, I'm interested in the ring.", timeAgo: "9:40 AM" },
      { id: "m2", fromMe: false, text: "Can we meet on campus?", timeAgo: "9:41 AM" },
    ],
  },
  {
    id: "c3",
    author: {
      id: "euphorium-support",
      name: "Euphorium Support",
      handle: "euphorium",
      verified: true,
      tier: "premium",
    },
    lastMessage: "Your dispute has been updated.",
    timeAgo: "1h",
    category: "system",
    messages: [
      { id: "m1", fromMe: false, text: "Your dispute has been updated.", timeAgo: "8:15 AM" },
      { id: "m2", fromMe: false, text: "Our team will resolve this within 48 hours.", timeAgo: "8:15 AM" },
    ],
  },
  {
    id: "c4",
    author: {
      id: "campus-threads",
      name: "Campus Threads",
      handle: "campusthreads",
      verified: true,
      tier: "business",
    },
    lastMessage: "Sure, I can hold it for you till tomorrow.",
    timeAgo: "3h",
    category: "seller",
    messages: [
      { id: "m1", fromMe: true, text: "Is the jacket still in size M?", timeAgo: "1:10 PM" },
      { id: "m2", fromMe: false, text: "Yes, just one left.", timeAgo: "1:15 PM" },
      { id: "m3", fromMe: true, text: "Can you hold it till tomorrow?", timeAgo: "1:16 PM" },
      { id: "m4", fromMe: false, text: "Sure, I can hold it for you till tomorrow.", timeAgo: "1:20 PM" },
    ],
  },
  {
    id: "c5",
    author: {
      id: "gadget-plug",
      name: "Gadget Plug",
      handle: "gadgetplug",
      verified: true,
      tier: "premium",
    },
    lastMessage: "Video walkthrough sent for verification.",
    timeAgo: "5h",
    category: "seller",
    messages: [
      { id: "m1", fromMe: false, text: "Hi! Since this is above ₦30,000, we'll need a quick verification step.", timeAgo: "11:00 AM" },
      { id: "m2", fromMe: false, text: "Video walkthrough sent for verification.", timeAgo: "11:32 AM" },
    ],
  },
  {
    id: "c6",
    author: {
      id: "amaka",
      name: "Amaka Eze",
      handle: "amaka.eze",
      verified: false,
      tier: "unverified",
    },
    lastMessage: "Do you deliver to Ile-Ife?",
    timeAgo: "1d",
    category: "buyer",
    messages: [
      { id: "m1", fromMe: false, text: "Hi, I saw your book bundle listing.", timeAgo: "Yesterday" },
      { id: "m2", fromMe: false, text: "Do you deliver to Ile-Ife?", timeAgo: "Yesterday" },
    ],
  },
];

export const notifications: AppNotification[] = [
  {
    id: "n1",
    type: "order",
    title: "Order Delivered",
    detail: "Confirm receipt to release payment to the seller.",
    timeAgo: "2m",
  },
  {
    id: "n2",
    type: "payment",
    title: "Payment Locked",
    detail: "Your payment of ₦320,000 is secured in Lockbox.",
    timeAgo: "12m",
  },
  {
    id: "n3",
    type: "message",
    title: "New Message",
    detail: "You have a new message from a seller.",
    timeAgo: "30m",
  },
  {
    id: "n4",
    type: "promo",
    title: "Promotions",
    detail: "New deals in your favorite category.",
    timeAgo: "1h",
  },
  {
    id: "n5",
    type: "message",
    title: "Campus Threads replied",
    detail: "\"Sure, I can hold it for you till tomorrow.\"",
    timeAgo: "3h",
  },
  {
    id: "n6",
    type: "order",
    title: "Dispute Update",
    detail: "Euphorium Support responded to your dispute on order #EUP87657.",
    timeAgo: "5h",
  },
  {
    id: "n7",
    type: "payment",
    title: "Payment Released",
    detail: "₦200,000 was released to the seller for order #EUP87656.",
    timeAgo: "1d",
  },
];
